### ISSUE TITLE
秋神怎么不搞一下gcc工具链

### ISSUE THREAD

**Issue by ShiauweiZhao** [loveuav/BlueSkyFlightControl#1]

**Comment by loveuav** [comment]
要搞的东西太多了，集中精力把目前最需要做的工作完成先。

**Comment by ShiauweiZhao** [comment]
其实我觉得405的算力还是有点渣的 ，可以考虑换个更好的片子  405 跑个12阶的ekf就要0.7ms的样子，后面开发起来应该不会太爽

**Comment by loveuav** [comment]
这套飞控目前不会用到这么高维的卡尔曼，算法不是越复杂越好，比如卡尔曼最重要的是误差模型而不是维数。
我估计飞控的稳定版本出来后，CPU占用率在40%左右（目前才20%多），所以基本够用了。

后面的另外一个项目可能会用STM32F7甚至RT1052，不过是有原因的。

**Comment by ShiauweiZhao** [comment]
12阶的ekf也不算啥多高维啊，难道 6阶 7阶ekf跑ahrs么

**Comment by allentintin** [comment]
GCC工具链，你要搞什么？

**Comment by ShiauweiZhao** [comment]
@allentintin mdk的armcc编译器bug太多

**Comment by JcZou** [comment]
mdk的armcc还不是免费的 需要license
